const data = [
  {
    id: 1,
    name: 'Badger Boots',
    image: 'https://vignette.wikia.nocookie.net/tibia/images/c/c5/Badger_Boots.gif/revision/latest?cb=20150624120056&path-prefix=en',
    arm: '2',
    weight: '12.00',
    attributes: 'speed +10',
    resist: null,
    imbuing_slots: '1',
    required_level: '60',
    required_vocation: null,
    dropped_by: [
      'Feroxa',
      'Feroxa (Gloom Wolf)Sharpclaw',
      'The Baron from Below',
      'Werebadger',
    ],
  },
  {
    id: 2,
    name: 'Boots of Haste',
    image: 'https://vignette.wikia.nocookie.net/tibia/images/1/1a/Boots_of_Haste.gif/revision/latest?cb=20050604051759&path-prefix=en',
    arm: '0',
    weight: '7.50',
    attributes: 'speed +20',
    resist: null,
    imbuing_slots: '1',
    required_level: null,
    required_vocation: null,
    dropped_by: [
      'Black Knight',
      'Blood Hand',
      'Blood Priest',
      'Broken Shaper',
      'Enfeebled Silencer',
      'Feroxa',
      'Ferumbras',
      'Golgordan',
      'Hand of Cursed Fate',
      'Hellgorak',
      'Hydra',
      'King Zelos',
      'Latrivan',
      'Lloyd',
      'Lokathmor',
      'Mad Mage',
      'Madareth',
      'Morgaroth',
      'Necromancer',
      'Necropharus',
      'Nightmare',
      'Nightstalker',
      'Nymph',
      'Omruc',
      'Orshabaal',
      'Raging Mage',
      'Shadow Pupil',
      'Silencer',
      'Swan Maiden',
      'Terofar',
      'The Welter',
      'Tormentor',
      'Ushuriel',
      'Vampire Bride',
      'Yakchal',
      'Zugurosh',
      'Zushuka',
    ],
  },
  {
    id: 3,
    name: 'Boots of Homecoming',
    image: 'https://vignette.wikia.nocookie.net/tibia/images/8/86/Boots_of_Homecoming.gif/revision/latest?cb=20151112143148&path-prefix=en',
    arm: '2',
    weight: '16.00',
    attributes: null,
    resist: null,
    imbuing_slots: null,
    required_level: '100',
    required_vocation: null,
    dropped_by: [
      'Ferumbras Mortal Shell',
    ],
  },
  {
    id: 4,
    name: 'Boots of Homecoming (Used)',
    image: 'https://vignette.wikia.nocookie.net/tibia/images/5/5d/Boots_of_Homecoming_%28Used%29.gif/revision/latest?cb=20160103152302&path-prefix=en',
    arm: '2',
    weight: '16.00',
    attributes: null,
    resist: null,
    imbuing_slots: null,
    required_level: '100',
    required_vocation: null,
    dropped_by: null,
  },
  {
    id: 5,
    name: 'Boots of Waterwalking',
    image: 'https://vignette.wikia.nocookie.net/tibia/images/7/7e/Boots_of_Waterwalking.gif/revision/latest?cb=20060310214923&path-prefix=en',
    arm: '0',
    weight: '7.70',
    attributes: null,
    resist: null,
    imbuing_slots: null,
    required_level: null,
    required_vocation: null,
    dropped_by: null,
  },
  {
    id: 6,
    name: 'Bunnyslippers',
    image: 'https://vignette.wikia.nocookie.net/tibia/images/a/aa/Bunnyslippers.gif/revision/latest?cb=20180305140931&path-prefix=en',
    arm: '0',
    weight: '6.00',
    attributes: null,
    resist: null,
    imbuing_slots: '1',
    required_level: null,
    required_vocation: null,
    dropped_by: [
      'Yeti',
    ],
  },
  {
    id: 7,
    name: 'Cobra Boots',
    image: 'https://vignette.wikia.nocookie.net/tibia/images/9/9e/Cobra_Boots.gif/revision/latest?cb=20190701193329&path-prefix=en',
    arm: '3',
    weight: '9.00',
    attributes: 'speed +10',
    resist: 'physical +6%',
    imbuing_slots: '1',
    required_level: '220',
    required_vocation: 'knights',
    dropped_by: [
      'Guard Captain Quaid',
      'Ugly Monster',
    ],
  },
  {
    id: 8,
    name: 'Coconut Shoes',
    image: 'https://vignette.wikia.nocookie.net/tibia/images/4/4f/Coconut_Shoes.gif/revision/latest?cb=20090601123458&path-prefix=en',
    arm: '0',
    weight: '6.00',
    attributes: null,
    resist: null,
    imbuing_slots: '1',
    required_level: null,
    required_vocation: null,
    dropped_by: [
      'Dryad',
    ],
  },
  {
    id: 9,
    name: 'Crocodile Boots',
    image: 'https://vignette.wikia.nocookie.net/tibia/images/3/3e/Crocodile_Boots.gif/revision/latest?cb=20051004233115&path-prefix=en',
    arm: '1',
    weight: '9.00',
    attributes: null,
    resist: null,
    imbuing_slots: '1',
    required_level: null,
    required_vocation: null,
    dropped_by: [
      'Crocodile',
      'Killer Caiman',
      'The Snapper',
    ],
  },
  {
    id: 10,
    name: 'Crystal Boots',
    image: 'https://vignette.wikia.nocookie.net/tibia/images/b/bb/Crystal_Boots.gif/revision/latest?cb=20091204231507&path-prefix=en',
    arm: '3',
    weight: '18.50',
    attributes: null,
    resist: 'ice +3%, energy -3%',
    imbuing_slots: '1',
    required_level: '70',
    required_vocation: 'knights and paladins',
    dropped_by: [
      'Chizzoron the Distorter',
    ],
  },
  {
    id: 11,
    name: 'Depth Calcei',
    image: 'https://vignette.wikia.nocookie.net/tibia/images/e/e7/Depth_Calcei.gif/revision/latest?cb=20111201000724&path-prefix=en',
    arm: '3',
    weight: '37.00',
    attributes: 'speed -5',
    resist: 'physical +5%',
    imbuing_slots: '1',
    required_level: '150',
    required_vocation: 'knights',
    dropped_by: [
      'Jaul',
    ],
  },
  {
    id: 12,
    name: 'Dragon Scale Boots',
    image: 'https://vignette.wikia.nocookie.net/tibia/images/e/e1/Dragon_Scale_Boots.gif/revision/latest?cb=20091204231446&path-prefix=en',
    arm: '3',
    weight: '18.50',
    attributes: null,
    resist: 'fire +3%, ice -3%',
    imbuing_slots: '1',
    required_level: '70',
    required_vocation: 'knights and paladins',
    dropped_by: [
      'Zulazza the Corruptor',
    ],
  },
  {
    id: 13,
    name: 'Draken Boots',
    image: 'https://vignette.wikia.nocookie.net/tibia/images/8/86/Draken_Boots.gif/revision/latest?cb=20100618072303&path-prefix=en',
    arm: '3',
    weight: '25.00',
    attributes: 'speed +15',
    resist: null,
    imbuing_slots: '1',
    required_level: '80',
    required_vocation: 'knights and paladins',
    dropped_by: [
      'Draken Abomination',
      'Draken Elite',
      'Soul of Dragonking Zyrtarch',
    ],
  },
  {
    id: 14,
    name: 'Filthy Bunnyslippers',
    image: 'https://vignette.wikia.nocookie.net/tibia/images/a/ac/Filthy_Bunnyslippers.gif/revision/latest?cb=20161108195936&path-prefix=en',
    arm: '0',
    weight: '6.00',
    attributes: null,
    resist: null,
    imbuing_slots: null,
    required_level: null,
    required_vocation: null,
    dropped_by: null,
  },
  {
    id: 15,
    name: 'Firewalker Boots',
    image: 'https://vignette.wikia.nocookie.net/tibia/images/4/4d/Firewalker_Boots.gif/revision/latest?cb=20081212102232&path-prefix=en',
    arm: '2',
    weight: '9.50',
    attributes: null,
    resist: 'Fire Field 90%',
    imbuing_slots: null,
    required_level: '130',
    required_vocation: null,
    dropped_by: null,
  },
  {
    id: 16,
    name: 'Fish Tail (Equipped)',
    image: 'https://vignette.wikia.nocookie.net/tibia/images/8/8b/Fish_Tail_%28Equipped%29.gif/revision/latest?cb=20180228195949&path-prefix=en',
    arm: '0',
    weight: '2.50',
    attributes: 'speed +300',
    resist: null,
    imbuing_slots: null,
    required_level: null,
    required_vocation: null,
    dropped_by: null,
  },
  {
    id: 17,
    name: 'Fish Tail (Unequipped)',
    image: 'https://vignette.wikia.nocookie.net/tibia/images/d/db/Fish_Tail_%28Unequipped%29.gif/revision/latest?cb=20180228195947&path-prefix=en',
    arm: '0',
    weight: '2.50',
    attributes: null,
    resist: null,
    imbuing_slots: null,
    required_level: null,
    required_vocation: null,
    dropped_by: null,
  },
  {
    id: 18,
    name: 'Fur Boots',
    image: 'https://vignette.wikia.nocookie.net/tibia/images/3/34/Fur_Boots.gif/revision/latest?cb=20070623042407&path-prefix=en',
    arm: '2',
    weight: '12.00',
    attributes: 'speed -6',
    resist: null,
    imbuing_slots: '1',
    required_level: null,
    required_vocation: null,
    dropped_by: [
      'Barbarian Bloodwalker',
      'Barbarian Brutetamer',
      'Barbarian Headsplitter',
      'Barbarian Skullhunter',
      'Bloodback',
    ],
  },
  {
    id: 19,
    name: 'Glacier Shoes',
    image: 'https://vignette.wikia.nocookie.net/tibia/images/f/f3/Glacier_Shoes.gif/revision/latest?cb=20071215064156&path-prefix=en',
    arm: '2',
    weight: '7.50',
    attributes: null,
    resist: 'ice +5%, energy -5%',
    imbuing_slots: '1',
    required_level: '35',
    required_vocation: 'sorcerers and druids',
    dropped_by: [
      'Hirintror',
      'Ice Witch',
      'Icecold Book',
      'Many Faces',
      'Seacrest Serpent',
      'Soul-Broken Harbinger',
      'Zushuka',
    ],
  },
  {
    id: 20,
    name: 'Golden Boots',
    image: 'https://vignette.wikia.nocookie.net/tibia/images/d/d4/Golden_Boots.gif/revision/latest?cb=20141219180549&path-prefix=en',
    arm: '4',
    weight: '31.00',
    attributes: null,
    resist: null,
    imbuing_slots: '1',
    required_level: null,
    required_vocation: null,
    dropped_by: [
      'Ghazbaran',
      'Zugurosh',
    ],
  },
  {
    id: 21,
    name: 'Guardian Boots',
    image: 'https://vignette.wikia.nocookie.net/tibia/images/1/17/Guardian_Boots.gif/revision/latest?cb=20091207120027&path-prefix=en',
    arm: '3',
    weight: '22.50',
    attributes: null,
    resist: 'physical +2%, holy -2%',
    imbuing_slots: '1',
    required_level: '70',
    required_vocation: 'knights and paladins',
    dropped_by: [
      'Ethershreck',
      'Ghastly Dragon',
      'Hatebreeder',
      'The Time Guardian',
    ],
  },
  {
    id: 22,
    name: 'Leather Boots',
    image: 'https://vignette.wikia.nocookie.net/tibia/images/9/94/Leather_Boots.gif/revision/latest?cb=20050523051338&path-prefix=en',
    arm: '1',
    weight: '9.00',
    attributes: null,
    resist: null,
    imbuing_slots: '1',
    required_level: null,
    required_vocation: null,
    dropped_by: [
      'Big Boss Trolliver',
      'Dwarf Guard',
      'Elf',
      'Island Troll',
      'Swamp Troll',
      'Troll Champion',
      'Troll Marauder',
      'Troll',
      'Witch',
      'Young Troll',
    ],
  },
  {
    id: 23,
    name: 'Lightning Boots',
    image: 'https://vignette.wikia.nocookie.net/tibia/images/4/46/Lightning_Boots.gif/revision/latest?cb=20071218060630&path-prefix=en',
    arm: '2',
    weight: '7.50',
    attributes: null,
    resist: 'energy +5%, earth -5%',
    imbuing_slots: '1',
    required_level: '35',
    required_vocation: 'sorcerers and druids',
    dropped_by: [
      'Burning Gladiator',
      'Cursed Prospector',
      'Elder Wyrm',
      'Energetic Book',
      'Gravelord Oshuran',
      'Lich',
      'Mazzinor',
      'Omrafir',
      'Prince Drazzak',
      'War Golem',
    ],
  },
  {
    id: 24,
    name: 'Magma Boots',
    image: 'https://vignette.wikia.nocookie.net/tibia/images/e/eb/Magma_Boots.gif/revision/latest?cb=20071215072048&path-prefix=en',
    arm: '2',
    weight: '7.50',
    attributes: null,
    resist: 'fire +5%, ice -5%',
    imbuing_slots: '1',
    required_level: '35',
    required_vocation: 'sorcerers and druids',
    dropped_by: [
      'Burning Gladiator',
      'Count Vlarkorth',
      'Crazed Summer Vanguard',
      'Dragon Lord Hatchling',
      'Feral Sphinx',
      'Hellflayer',
      'Hellhound',
      'Infernal Demon',
      'Infernalist',
      'Lava Golem',
      'Magma Crawler',
      'Manticore',
      'Massive Fire Elemental',
      'Orc Warlord',
      'Sphinx',
      'The Souldespoiler',
      'Warlord Ruzad',
    ],
  },
  {
    id: 25,
    name: 'Metal Spats',
    image: 'https://vignette.wikia.nocookie.net/tibia/images/8/85/Metal_Spats.gif/revision/latest?cb=20140615103926&path-prefix=en',
    arm: '1',
    weight: '18.00',
    attributes: null,
    resist: 'physical +1%',
    imbuing_slots: '1',
    required_level: '50',
    required_vocation: 'knights and paladins',
    dropped_by: [
      'Bellicose Orger',
      'Glooth Battery',
      'Metal Gargoyle',
      'Ogre Ruffian',
      'Walker',
    ],
  },
  {
    id: 26,
    name: 'Oriental Shoes',
    image: 'https://vignette.wikia.nocookie.net/tibia/images/0/0d/Oriental_Shoes.gif/revision/latest?cb=20150624093146&path-prefix=en',
    arm: '2',
    weight: '5.00',
    attributes: 'speed +15',
    resist: null,
    imbuing_slots: '1',
    required_level: '80',
    required_vocation: 'sorcerers and druids',
    dropped_by: [
      'Dawnfire Asura',
      'Frost Flower Asura',
      'Midnight Asura',
      'Ravennous Hunger',
      'The Blazing Rose',
      'The Flaming Orchid',
      'True Dawnfire Asura',
      'True Frost Flower Asura',
      'True Midnight Asura',
    ],
  },
  {
    id: 27,
    name: 'Pair of Dreamwalkers',
    image: 'https://vignette.wikia.nocookie.net/tibia/images/5/53/Pair_of_Dreamwalkers.gif/revision/latest?cb=20181106184616&path-prefix=en',
    arm: '2',
    weight: '8.00',
    attributes: 'magic level +1',
    resist: 'earth +8%',
    imbuing_slots: '1',
    required_level: '180',
    required_vocation: 'sorcerers and druids',
    dropped_by: [
      'Alptramun',
    ],
  },
  {
    id: 28,
    name: 'Pair of Nightmare Boots',
    image: 'https://vignette.wikia.nocookie.net/tibia/images/e/ec/Pair_of_Nightmare_Boots.gif/revision/latest?cb=20191108184638&path-prefix=en',
    arm: '2',
    weight: '13.00',
    attributes: 'magic level +1',
    resist: 'energy +6%',
    imbuing_slots: '1',
    required_level: '140',
    required_vocation: 'sorcerers and druids',
    dropped_by: [
      'Irgix the Flimsy',
      'The Dread Maiden',
      'The Pale Worm',
      'Unaz the Mean',
      'Vok the Freakish',
    ],
  },
  {
    id: 29,
    name: 'Pair of Soft Boots',
    image: 'https://vignette.wikia.nocookie.net/tibia/images/2/2d/Pair_of_Soft_Boots.gif/revision/latest?cb=20170905180404&path-prefix=en',
    arm: '0',
    weight: '8.00',
    attributes: 'faster regeneration',
    resist: null,
    imbuing_slots: null,
    required_level: null,
    required_vocation: null,
    dropped_by: null,
  },
  {
    id: 30,
    name: 'Pair of Soulstalkers',
    image: 'https://vignette.wikia.nocookie.net/tibia/images/c/cb/Pair_of_Soulstalkers.gif/revision/latest?cb=20200611023034&path-prefix=en',
    arm: '3',
    weight: '13.00',
    attributes: 'distance fighting +1, speed +20',
    resist: 'physical +5%',
    imbuing_slots: '1',
    required_level: '400',
    required_vocation: 'paladins',
    dropped_by: null,
  },
  {
    id: 31,
    name: 'Pair of Soulwalkers',
    image: 'https://vignette.wikia.nocookie.net/tibia/images/3/33/Pair_of_Soulwalkers.gif/revision/latest?cb=20200611023032&path-prefix=en',
    arm: '4',
    weight: '13.00',
    attributes: 'sword fighting +1, club fighting +1, axe fighting +1, speed +15',
    resist: 'physical +7%, fire +5%',
    imbuing_slots: '1',
    required_level: '400',
    required_vocation: 'knights',
    dropped_by: null,
  },
  {
    id: 32,
    name: 'Patched Boots',
    image: 'https://vignette.wikia.nocookie.net/tibia/images/0/04/Patched_Boots.gif/revision/latest?cb=20080623075109&path-prefix=en',
    arm: '2',
    weight: '10.00',
    attributes: null,
    resist: null,
    imbuing_slots: '1',
    required_level: null,
    required_vocation: null,
    dropped_by: null,
  },
  {
    id: 33,
    name: 'Pirate Boots',
    image: 'https://vignette.wikia.nocookie.net/tibia/images/5/54/Pirate_Boots.gif/revision/latest?cb=20170905180530&path-prefix=en',
    arm: '2',
    weight: '8.00',
    attributes: null,
    resist: null,
    imbuing_slots: '1',
    required_level: null,
    required_vocation: null,
    dropped_by: [
      'Pirate Corsair',
    ],
  },
  {
    id: 34,
    name: 'Prismatic Boots',
    image: 'https://vignette.wikia.nocookie.net/tibia/images/7/7f/Prismatic_Boots.gif/revision/latest?cb=20120622164103&path-prefix=en',
    arm: '3',
    weight: '18.00',
    attributes: 'speed +15',
    resist: 'death +3%',
    imbuing_slots: '1',
    required_level: '150',
    required_vocation: 'paladins',
    dropped_by: null,
  },
  {
    id: 35,
    name: 'Sandals',
    image: 'https://vignette.wikia.nocookie.net/tibia/images/a/af/Sandals.gif/revision/latest?cb=20120403183449&path-prefix=en',
    arm: '0',
    weight: '6.00',
    attributes: null,
    resist: null,
    imbuing_slots: '1',
    required_level: null,
    required_vocation: null,
    dropped_by: [
      'Dark Monk',
      'Elf Arcanist',
      'Elf Scout',
      'Fernfang',
      'Monk',
      'Monk of the Order',
    ],
  },
  {
    id: 36,
    name: 'Steel Boots',
    image: 'https://vignette.wikia.nocookie.net/tibia/images/d/d7/Steel_Boots.gif/revision/latest?cb=20170905181059&path-prefix=en',
    arm: '3',
    weight: '29.00',
    attributes: null,
    resist: null,
    imbuing_slots: '1',
    required_level: null,
    required_vocation: null,
    dropped_by: [
      'Behemoth',
      'Bretzecutioner',
      'Cliff Strider',
      'Control Tower',
      'Dark Torturer',
      'Destroyer',
      'Eradicator',
      'Fury',
      'Glooth Battery',
      'Gorzindel',
      'Grimeleech',
      'Grorlam',
      'Hellgorak',
      'Hive Overseer',
      'Horadron',
      'Kollos',
      'Morgaroth',
      'Morguthis',
      'Omrafir',
      'Plaguesmith',
      'Prince Drazzak',
      'Retching Horror',
      'Shaburak Lord',
      'Shaburak Prince',
      'Sight of Surrender',
      'Stonecracker',
      'Terofar',
      'The Handmaiden',
      'Walker',
      'War Golem',
      'Zugurosh',
    ],
  },
  {
    id: 37,
    name: 'Terra Boots',
    image: 'https://vignette.wikia.nocookie.net/tibia/images/a/af/Terra_Boots.gif/revision/latest?cb=20071218061146&path-prefix=en',
    arm: '2',
    weight: '7.50',
    attributes: null,
    resist: 'earth +5%, fire -5%',
    imbuing_slots: '1',
    required_level: '35',
    required_vocation: 'sorcerers and druids',
    dropped_by: [
      'Armadile',
      'Choking Fear',
      'Cobra Vizier',
      'Cursed Book',
      'Deathbine',
      'Dwarf Geomancer',
      'Enfeebled Silencer',
      'Ghastly Dragon',
      'Glooth Bandit',
      'Glooth Brigand',
      'Hideous Fungus',
      'Humongous Fungus',
      'Ink Blob',
      'Lost Basher',
      'Lost Berserker',
      'Lost Exile',
      'Lost Husher',
      'Ogre Sage',
      'Omnivora',
      'Silencer',
      'Terofar',
      'Thanatursus',
    ],
  },
  {
    id: 38,
    name: 'Treader of Torment',
    image: 'https://vignette.wikia.nocookie.net/tibia/images/0/0c/Treader_of_Torment.gif/revision/latest?cb=20151112195350&path-prefix=en',
    arm: '4',
    weight: '36.00',
    attributes: null,
    resist: null,
    imbuing_slots: '1',
    required_level: null,
    required_vocation: null,
    dropped_by: [
      'Shulgrax',
    ],
  },
  {
    id: 39,
    name: 'Vampire Silk Slippers',
    image: 'https://vignette.wikia.nocookie.net/tibia/images/0/00/Vampire_Silk_Slippers.gif/revision/latest?cb=20130903162133&path-prefix=en',
    arm: '0',
    weight: '11.50',
    attributes: null,
    resist: null,
    imbuing_slots: '1',
    required_level: null,
    required_vocation: null,
    dropped_by: [
      'The Pale Count',
    ],
  },
  {
    id: 40,
    name: 'Void Boots',
    image: 'https://vignette.wikia.nocookie.net/tibia/images/f/f7/Void_Boots.gif/revision/latest?cb=20160425192050&path-prefix=en',
    arm: '2',
    weight: '15.00',
    attributes: 'faster Regeneration, speed +30',
    resist: 'energy +10%',
    imbuing_slots: null,
    required_level: '150',
    required_vocation: null,
    dropped_by: [
      'Anomaly',
      'Eradicator',
      'Outburst',
      'Realityquake',
      'Rupture',
      'World Devourer',
    ],
  },
  {
    id: 41,
    name: 'Winged Boots',
    image: 'https://vignette.wikia.nocookie.net/tibia/images/a/ac/Winged_Boots.gif/revision/latest?cb=20190701193855&path-prefix=en',
    arm: '2',
    weight: '12.00',
    attributes: 'speed +15, distance fighting +1',
    resist: 'earth +7%',
    imbuing_slots: '1',
    required_level: '220',
    required_vocation: 'paladins',
    dropped_by: [
      'Urmahlullu the Weakened',
      'Bragrumol',
      'Xogixath',
    ],
  },
  {
    id: 42,
    name: 'Yetislippers',
    image: 'https://vignette.wikia.nocookie.net/tibia/images/3/38/Yetislippers.gif/revision/latest?cb=20181212132919&path-prefix=en',
    arm: null,
    weight: '7.40',
    attributes: null,
    resist: null,
    imbuing_slots: null,
    required_level: null,
    required_vocation: null,
    dropped_by: [
      'Baleful Bunny',
    ],
  },
  {
    id: 43,
    name: 'Zaoan Shoes',
    image: 'https://vignette.wikia.nocookie.net/tibia/images/a/ad/Zaoan_Shoes.gif/revision/latest?cb=20091130191612&path-prefix=en',
    arm: '1',
    weight: '7.00',
    attributes: 'speed +5',
    resist: null,
    imbuing_slots: '1',
    required_level: null,
    required_vocation: null,
    dropped_by: [
      'Battlemaster Zunzu',
      'Draken Spellweaver',
      'Draken Warmaster',
      'Ethershreck',
      'Fazzrah',
      'Flamecaller Zazrak',
      'Ghastly Dragon',
      'Hatebreeder',
      'Lizard Chosen',
      'Lizard Dragon Priest',
      'Lizard Gate Guardian',
      'Lizard High Guard',
      'Lizard Legionnaire',
      'Lizard Zaogun',
      'The Voice of Ruin',
    ],
  },
]

export default data
